src/AppEngineDeploymentTrait.php
This allows us to set `GOOGLE_DEPLOYMENT_DELAY=5` for e2e tests, to fix the `502` failing tests on jenkins until the issue is fixed in App Engine Flex.
=> Possible fix for flex 502s

src/AppEngineDeploymentTrait.php
In order to move `getting-started-php` to use `php-tools`, we need to allow a custom `app.yaml`
=> adds do deploy to allow alternate ways to call deploy

composer.json
When I tried to have this tool into a laravel based app, there was a conflict on the phpunit versions. We should not have phpunit on the main dependency section. We still have it in `requrie-dev`.
=> Removed phpunit:~5.0 from the depenency section

src/Utils/Flex/flex_exec
The command failed when it's installed into the vendor directory.
=> Fixed the autoload path for vendor dir instalation

src/TestUtils/EventuallyConsistentTestTrait.php
This is a better way to handle backing off, and also it will fix quota limit tests
=> Use exponential instead of linear backoff

composer.json, src/TestUtils/AppEngineDeploymentTrait.php, src/TestUtils/GcloudWrapper.php, test/TestUtils/GcloudWrapperTest.php
- Allows for deployments to be skipped in deployment tests by setting `GOOGLE_SKIP_DEPLOYMENT=true`
- Allows `install_test_deps.sh` to be run using `vendor/bin/intall_test_deps.sh`
- Cleans up CS
=> Allows skipping deployment

composer.json, src/TestUtils/ExecuteCommandTrait.php, src/TestUtils/ExponentialBackoffTrait.php, src/TestUtils/TestTrait.php, test/TestUtils/ExecuteCommandTraitTest.php, test/TestUtils/ExponentialBackoffTraitTest.php, test/TestUtils/TestTraitTest.php, test/TestUtils/command.php
Adds a few traits I think we'll find useful for all our samples. They allow us to check environment variables, run commands, and retry APIs when they throw `RESOURCE_EXHAUSTED`
=> adds Test Helper traits

composer.json
Greetings 👋,
[Guzzle 7.0 has just been released](https://github.com/guzzle/guzzle/releases), this change widens the version constraint so that it can be used here and in other Google PHP libraries using the PHP Tools.
A new client is instantiated in [TestUtils/DeploymentTrait.php](https://github.com/GoogleCloudPlatform/php-tools/blob/master/src/TestUtils/DeploymentTrait.php) and in [TestUtils/DevAppserverTestTrait.php](https://github.com/GoogleCloudPlatform/php-tools/blob/master/src/TestUtils/DevAppserverTestTrait.php) - since the `base_uri` client config parameter hasn't changed, this should continue working as before.
:octocat:
=> Add support for Guzzle 7.x

scripts/install_test_deps.sh
`gcloud` has removed the component `app-engine-php`. We must remove the installation of this component so the gcloud install script can succeed
=> fix: remove deprecated app-engine-php component

src/TestUtils/CloudFunctionDeploymentTrait.php, src/TestUtils/GcloudWrapper/AppEngine.php, src/TestUtils/GcloudWrapper/CloudFunction.php, src/TestUtils/GcloudWrapper/CloudRun.php, src/TestUtils/GcloudWrapper/GcloudWrapperTrait.php
This is initial support for end-to-end testing support for Cloud Functions. It provides the expected lifecycle management to deploy and delete the function.
* Creates `Google\Cloud\TestUtils\GcloudWrapper\CloudFunction.php` to provide capability.
* Creates `Google\Cloud\TestUtils\CloudFunctionDeploymentTrait.php` to provide default implementation.
* Imposes some code style standards on other files in `Google\Cloud\TestUtils\GcloudWrapper`, along with a few comment corrections.
```php
<?php
namespace Google\Cloud\Samples\Functions\Helloworld;
use Google\Cloud\TestUtils\CloudFunctionDeploymentTrait;
use Google\Cloud\TestUtils\EventuallyConsistentTestTrait;
use PHPUnit\Framework\TestCase;
/**
* Class DeployTest.
*/
class DeployTest extends TestCase
{
use CloudFunctionDeploymentTrait;
use …
```
=> feat(functions): add testing support for Functions

src/TestUtils/CloudFunctionDeploymentTrait.php, src/TestUtils/GcloudWrapper/CloudFunction.php
Fixes #87 
This change allows appending deployment flags to a Cloud Function deploy.
It also fixes it so you can iteratively run deploy tests with `GOOGLE_KEEP_DEPLOYMENT` and `GOOGLE_SKIP_DEPLOYMENT` in order to test changes.
To append flags to the deploy command, simply add the following to your DeployTest.php:
```php
protected static function deployFlags(array $flags = []) : array
{
$flags['--update-env-vars'] = 'FOO=BAR,TEST=EV';
return $flags;
}
```
=> feat(functions): override arbitrary flags, run without deploy

src/TestUtils/CloudFunctionLocalTestTrait.php
Ideally, we could make this an option instead of overriding default behavior.
(If it won't break any existing samples, such "optional" behavior may not be worth it.)
=> chore(GCF test trait): don't throw on HTTP error

src/Utils/ContainerExec.php, test/Utils/ContainerExecTest.php, test/Utils/Flex/FlexExecCommandTest.php
Outdated:
`gcloud container builds submit`
Current
`gcloud builds submit`
=> fix(cloudbuild): Adapt syntax to implementation

src/TestUtils/CloudFunctionDeploymentTrait.php
=> chore(functions): Allow HTTP errors in deployment tests

src/TestUtils/CloudFunctionDeploymentTrait.php, src/TestUtils/CloudFunctionLocalTestTrait.php, src/TestUtils/GcloudWrapper/CloudFunction.php, src/TestUtils/GcloudWrapper/GcloudWrapperTrait.php
Core things enabled in this change: Cleaner CloudEvent DeployTests and generally cleaner SystemTest options.
* 🚨  **Breaking Changes:** `private static $name` in tests no longer works.
* 🚨  **Breaking Changes:** `CloudFunctionDeploymentTrait::deployFlags()` from #88 is dropped.
* 🚨  **Breaking Changes:** `CloudFunction:__construct()` and various other methods take different parameters.
* ✅  **New Feature:** `CloudFunction::getFunctionName()` is a public method providing the name of the function. It handles GOOGLE_VERSION_ID for you. This is useful to enable logging tests.
* ✅  **New Feature:** `CloudFunction::run()` now returns the process object so system tests can retrieve output using the very useful helper methods in Symfony's process component.
* 🗂️  **Refactor**: Rearranged …
=> refactor(functions)!: rearrange CloudFunction support

src/TestUtils/CloudFunctionDeploymentTrait.php, src/TestUtils/GcloudWrapper/CloudFunction.php
Move the `processFunctionLogs` function to the `php-tools` library.
Part of [this issue](https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1271).
=> feat(functions): add processFunctionLogs helper function

src/TestUtils/CloudFunctionDeploymentTrait.php
#104 lets us specify retry counts, so let's lower the default value (and raise it in tests themselves where necessary)
_This should speed up our `functions` CI builds._
=> chore(functions): decrease default retry count

src/TestUtils/ExecuteCommandTrait.php
"Shell command" functionality is used [here](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/standard/symfony-framework/test/DeploySymfonyTrait.php#L35), but is currently **unsupported** by this package.
_(This PR adds that support.)_
=> feat(test utils): support shell commands

src/Utils/WordPress/files/wp-config.php
AFAICT, `WP_DEBUG_LOG` files are inaccessible on App Engine. Let's recommend `WP_DEBUG_DISPLAY` instead?
=> chore(wordpress): clarify debug behavior on App Engine

src/TestUtils/AppEngineDeploymentTrait.php, src/TestUtils/DeploymentTrait.php
Fixes error in Kokoro deployment tests from incorrect function execution order (due to function inheritance)
Tested locally and this seems to fix the issue
=> fix: deploymenttrait execution order

src/TestUtils/GcloudWrapper/CloudFunction.php
Updates the invocation of functions for local testing with the new suggested method for functions framework, if the alternative `router.php` file exists. 
https://github.com/GoogleCloudPlatform/functions-framework-php/pull/163
Should resolve build errors like https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1936 where tests aren't succeeding for reasons unrelated to the sample code. 
(php not primary language, may not be most correct way to implementing this check.)
=> fix: opt to use functions framework router, if available

src/TestUtils/TestTrait.php
this will prevent the following deprecation warning in PHP 8.3+
```
Deprecated: Calling get_class() without arguments is deprecated in vendor/google/cloud-tools/src/TestUtils/TestTrait.php on line 127
```
=> chore: use __CLASS__ instead of get_class
